### ISSUE TITLE
shuffle conflicts with date view

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/pix-plot#115]
I'm not quite sure why, but it appears that specifying `--shuffle` at ingest time disables the date view from appearing. I can't find an obvious place in the code this interaction might happen, but leaving off only that shuffle parameter on the same images and metadata will cause the date layout to start working...

**Comment by duhaime** [comment]
Woof that's gnarly! I just tested with the oslo_mini dataset with fictitious integer dates, but passing `--shuffle` still allowed the date layout to display... 

Is there any chance you could publish your dataset to the [image datasets](https://github.com/YaleDHLab/image_datasets)? If so I'm happy to take a look!

**Comment by pleonard212** [comment]
Sure! The two files are:

http://pixplot.yale.edu/datasets/vestindien/images.tar
http://pixplot.yale.edu/datasets/vestindien/metadata.csv

What's interesting is, when `--shuffle` is not used, I see a bunch of parsedate warnings - which are a good sign, I think, because this dataset has many missing dates.  With `--shuffle`, I don't get those messages.

**Comment by duhaime** [comment]
Ah those files were super helpful. It turns out the date layout was checking only the first image's metadata to see if there was a date attribute. Shuffling reordered the images, so the first image could have or not have a date attribute in this dataset! I just set `0.0.84` to fix that behavior...

P.S. Here's a [first draft of a realtime layout](https://duhaime.s3.amazonaws.com/sketches/0ECAA20ECDBC4DEB82E9E1CE41D9A53B/index.html), parsing a sample IIIF manifest from the BNF. Still plenty to do on this front but here's a sketch!

**Comment by duhaime** [comment]
This is resolved
