### ISSUE TITLE
Resuming after crash

### ISSUE THREAD

**Issue by sitems** [YaleDHLab/pix-plot#141]
I started the process on 100 000 images, image features have been extracted, but then the script crashed due to memory error.

Can I somehow resume it so it will not need to compute image features again?

**Comment by duhaime** [comment]
@sitems yes, if you restart the processing, the computing process will find the image vectors you've already created and will refrain from recreating them. If you have any trouble getting that going, please let us know!

By the way, did you hit an OOM error while creating the "linear assignment" layout? For a few releases we were using a kind of experimental library to snap the UMAP projection to a grid. It turns out that library didn't scale well with memory, so we've switched back to rasterfairy for the task. That's all to say, if you run `python` then:
```
import pixplot
print(pixplot.__file__)
```
You'll see where the module was installed. You may wish to change the function `get_layouts()` such that the grid layout is determined by `get_rasterfairy_layout()` rather than `get_lap_layout()`. It's totally up to you though!

**Comment by sitems** [comment]
@duhaime  Thank you for very fast reply, resuming the process works.

Regarding the memory error, it was in the last step of the process, but the problem was on my side, since I didn't have enough free memory.

By the way, thank you for excellent library, I am working with images a lot, so I really appreciate it. The visualization and clustering are perfect.

**Comment by duhaime** [comment]
Thanks very much for your kind words @sitems! I'm glad the process worked out. Happy plotting!

**Comment by duhaime** [comment]
@sitems I'm going to close this issue out but if other troubles arise in the future please feel free to raise new issues!
