### ISSUE TITLE
tf_pose requirement of TensorRT does not have Python API available on Windows

### ISSUE THREAD

**Issue by fr1ll** [YaleDHLab/pix-plot#148]
It looks like tf_pose [requires TensorRT](https://github.com/tryagainconcepts/tf-pose-estimation/blob/master/tf_pose/estimator.py#L14). TensorRT is available on Windows, but the[ Python API is not](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html). This means the versions of PixPlot using tf_pose will not work on Windows, unfortunately.

**Comment by duhaime** [comment]
Thanks very much for the heads up on this @fr1ll! I think the play is to remove the tf_pose module from the dependencies in that case, and just have users install it if they want to build pose-aware plots...

**Comment by fr1ll** [comment]
Yes, sorry I wasn't able to propose a solution! In my case, I just installed a version just before the 'tf_pose' commit. I've done some looking for another ready-to-go pose prediction library, but haven't found one.

**Comment by duhaime** [comment]
No worries at all, just diagnosing the problem is super helpful. I just pushed an update so if you wanted you could `pip uninstall pixplot` then `pip install https://github.com/yaledhlab/pix-plot/archive/master.zip`. 

Thanks again for the heads up! I think this should be safe to close now, but if you see other issues please do send a flare!

**Comment by fr1ll** [comment]
Sounds good! 👍 I'll try this out tomorrow and if there's any unforeseen problem I'll re-open the issue.
