### ISSUE TITLE
Unable to zoom in much on new m1 macbook

### ISSUE THREAD

**Issue by stratospark** [YaleDHLab/pix-plot#162]
After upgrading to the new macbook, my plots started rendering differently. I'm not able to zoom in past a certain amount, the images retain a maximum point size of 64px.

Looking into it, I realized it was a limitation in the vertex shader of using `gl_PointSize` on GPUs with low Aliased Point Size Range. On this [Web GL Report tool](https://webglreport.com/), it shows that value to be `[1, 64]`. I've asked others what their values are and some reported 1024 or 8191.

I'm still a three.js newbie, though I've been learning a lot reading pix-plot code! Hypothetically, would this app still be able to perform as well using textured quads with zooming handled in the normal way through the camera?

![image](https://user-images.githubusercontent.com/93366/109231975-4a3b9180-777c-11eb-94d4-1a4cb2e1c248.png)

**Comment by duhaime** [comment]
This is a super interesting question @stratospark, and I'm glad you can make some sense of this crazy codebase!

Once upon a time we did in fact use textured quads, and it wouldn't be inconceivable to return to them. If they were "instanced" quads we shouldn't even have too much of a performance hit. (There's a [good overview of instancing here](https://medium.com/@pailhead011/instancing-with-three-js-36b4b62bc127) by the three.js community member @pailhead, who knows way more than I do!)

As a side note, we should in theory be rendering antialiased points since [we pass `antialias: true`](https://github.com/YaleDHLab/pix-plot/blob/master/pixplot/web/assets/js/tsne.js#L790) to the constructor of the renderer. I believe that should mean that `GL_SMOOTH_POINT_SIZE_RANGE` and possibly `GL_SMOOTH_POINT_SIZE_GRANULARITY` should be the limiting factors for point sizes (it looks like `GL_ALIASED_POINT_SIZE_RANGE` should set the bounds on aliased points, which we would render if we were to set `antialias: false` in the renderer constructor).

All that said, this shouldn't be too hard to switch. I'll take a look in the coming days and talk this through with the PixPlot team and will hope to follow up soon!

**Comment by duhaime** [comment]
@stratospark sorry for the delays on this issue. We've just pushed a pull request (https://github.com/YaleDHLab/pix-plot/commit/c7c48dd61eea8637b4fb7c41a49b0b2297130e39) that should allow one to display the images using GL_TRIANGLEs rather than GL_POINTs. 

In theory, this _should_ play more nicely with the new M1 Macs...

If you try it out and have thoughts, we'd certainly be grateful if you could follow up!

**Comment by duhaime** [comment]
@stratospark just circling back on this--if you have a second to try the latest master, it'd be great to hear about performance on the new M1!

**Comment by duhaime** [comment]
I'm going to close this out but please reopen it if necessary!
