### ISSUE TITLE
Idea: metadata on hover

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/pix-plot#38]
Chatting with @broadwell and we thought of something slightly different than the "deep link on click" use case: a hover state where a caption shows when you're mousing over each image. This might lend some context without a complete jump to a different page. (Wouldn't replace deep-link functionality.)

Presumably the metadata would either be at the top or the bottom of the screen (our current site design would support the top very easily).  This instead of an info box that followed the cursor, which we think would be distracting.

**Comment by tokee** [comment]
I prefer showing the meta-data near the image itself ( try zooming in on http://labs.statsbiblioteket.dk/juxta/subject208/ ), but it is not a clear-cut choice: It is distracting to have it near the image yes, but having it elsewhere forces the user to change focus. I like the idea of [ZoomWorld](https://flylib.com/books/en/4.378.1.42/1/), where there context switches are kept to a minimum.

Related: Hover is problematic on touch-devices. Explicit selection (touch an image) would probably be needed there. This would require the deep-link to be activated from the displayed meta-data, rather than being activated by clicking, but I find that to be a good thing: Presenting a collection in a tool such as PixPlot means a focus on the whole collection and the relation between the items; switching away from that view should not be a primary function.

**Comment by duhaime** [comment]
well we decided to try displaying metadata on click instead. I'll close this for now, but if anyone wants to revisit the metadata display trigger I'm happy to do so!
