### ISSUE TITLE
Clustering is calculated, but discarded

### ISSUE THREAD

**Issue by xmacex** [YaleDHLab/pix-plot#74]
For the visualization, the `utils/process_images.py` produces _plot_data.json_ file. In the program, the `write_json()` function calls `get_centroids()` which calculates a _k_-means clustering in the reduced space for the purposes of selecting an image to "summarise" each of the clusters, as "hotspots". However, the clustering is then discarded.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Iris_Flowers_Clustering_kMeans.svg/1920px-Iris_Flowers_Clustering_kMeans.svg.png)

It might, or it might not, be nice to keep the clustering results of _k_-means and store it for further use.

**Comment by xmacex** [comment]
Hold on I have a solution for this.

**Comment by duhaime** [comment]
Thanks very much @xmacex!

Yes, in some cases it could be nice to know an image's cluster (which is essentially a very lossy representation of its position in the higher dimensional space). I wasn't storing the memberships to date just because with lots of data the json packet was already pretty large, so any savings can be nice.

That said, I think this PR can help others, as this and other related questions have come up in the past (https://github.com/YaleDHLab/pix-plot/issues/65, https://github.com/YaleDHLab/pix-plot/issues/72). Thanks again for this!

**Comment by duhaime** [comment]
We now store cluster membership in `output/data/hotspots/hotspot-PLOT_ID.json` 🚀🚀🚀
