### ISSUE TITLE
Processing images failing on experimental

### ISSUE THREAD

**Issue by cncoleman** [YaleDHLab/pix-plot#89]
I'm getting AttributeError: module 'tensorflow_core._api.v2.config' has no attribute 'experimental_list_devices'. A keras issue?

**Comment by duhaime** [comment]
Thanks for the heads up @cncoleman! Yes, I think you're right--the Tensorflow version specification was a little too optimistic before. 

I just pushed 0.0.59 which pins it further and removes the line I believe was likely responsible for this (we were querying to see if the host device has one or more GPUs available, but since we aren't using that information it was simple enough to just remove that line). 

Could I please ask you to try: `pip install pixplot -U` and then try to reprocess your collection?

**Comment by cncoleman** [comment]
That seems to have solved the problem. But now another has arisen.
