### ISSUE TITLE
update atlasCounts in tsne-webgl.js

### ISSUE THREAD

**Issue by pleonard212** [YaleDHLab/pix-plot#9]
We may need to dynamically update this line:

`var atlasCounts = { '32px': 1, '64px': 3 }`

...upon completion of the atlas maps... I think right now it requires some manual adjustment.

**Comment by duhaime** [comment]
Amen, that was meant to go. For what it's worth, identifying the atlas counts a priori allows the page to start requesting atlas files immediately, whereas otherwise one has to wait until the JSON packet arrives to start fetching atlas files. This won't make a difference if one is running on localhost, but can make a big difference if the JSON is big and isn't tarzipped!

This should be all set on master now...

**Comment by pleonard212** [comment]
Great, thanks! I had another thought on the JSON packet, I'll put that in another thread...
