### ISSUE TITLE
Parsing the IIIF manifest assumes a 600x is available

### ISSUE THREAD

**Issue by cncoleman** [YaleDHLab/pix-plot#92]
I tried to import a set of IIIF manifests and it returned properly formed URLs for the images, except that, in this collection, the full size image is 400x, so the URLs return nothing.

**Comment by duhaime** [comment]
Ah sorry about that, I thought IIIF would resize an image into any requested size, but I guess there's a max width beyond which IIIF servers will no longer increase an image's size. So e.g.

```
# 5000 width works
https://images.britishart.yale.edu/iiif/95696475-8858-4b08-9b04-877cbe2f3e32/full/5000,/0/native.jpg

# 50000 width is too big
https://images.britishart.yale.edu/iiif/95696475-8858-4b08-9b04-877cbe2f3e32/full/50000,/0/native.jpg
```

I just pushed updates to the [iiif-downloader](https://github.com/YaleDHLab/iiif-downloader) package that's used herein. Could you try to `pip install iiif_downloader -U` and then retry the build command?

**Comment by duhaime** [comment]
@cncoleman Did you get a chance to try the new iiif downloader release? I wanted to make sure you were all set on that front...

**Comment by cncoleman** [comment]
It is still trying to load a jpg that does not exist. Then there is the refusing to overwrite manifest.json:
```
 * loading manifest from url https://purl.stanford.edu/bj642zg7120/iiif/manifest
 * saving manifest to iiif-downloads/manifests/manifest
 ! refusing to overwrite content at location iiif-downloads/manifests/manifest.json
 * loading image from url https://stacks.stanford.edu/image/iiif/bj642zg7120%2F99538_7A_PM/full/600,/0/default.jpg
 * saving iiif-downloads/images/iiif.png
```
Here is the full json for that image. It looks like the full size is not available and the largest available is 400/ 

`
{
  "@context": "http://iiif.io/api/image/2/context.json",
  "@id": "https://stacks.stanford.edu/image/iiif/bj642zg7120%252F99538_7A_PM",
  "protocol": "http://iiif.io/api/image",
  "width": 5676,
  "height": 3728,
  "sizes": [
    {
      "width": 400,
      "height": 262
    }
  ],
  "tiles": [
    {
      "width": 256,
      "height": 256,
      "scaleFactors": [
        1,
        2,
        4,
        8,
        16,
        32
      ]
    }
  ],
  "profile": [
    "http://iiif.io/api/image/2/level2",
    {
      "maxWidth": 400,
      "maxHeight": 400
    }
  ]
}
`

**Comment by duhaime** [comment]
@cncoleman many thanks for your follow up and the details of this manifest--I've learned more about IIIF because of this thread. I thought all IIIF servers would serve any size of an image <= the width and height for the given image advertised in the image's manifest, but I see now that an image can advertise discrete width and height attributes in its own metadata json. Curious!

I also had assumed the urls were more consistent but I see the prefix part of the scheme has some variability to it. 

I just pushed up a new version of the IIIF downloader with these corrections. You could please try `pip install iiif_downloader==0.0.8` and `rm -rf output` to clear the pixplot output. Then could you try to process the collection again? We should be getting closer now!

**Comment by cncoleman** [comment]
@duhaime Success with parsing the manifests and returning the images as .pngs. But the new directory of manifest.json files has strangely configured filenames. Here is an example: `https/||||purl.stanford.edu||pj116tz6918||iiif||manifest.json`
And when I spin up the server there is a 404 for /output/data/manifest.json.
