### ISSUE TITLE
Is it possible to maintain relative size among image thumbnails?

### ISSUE THREAD

**Issue by bado-lee** [YaleDHLab/pix-plot#94]
Hello again :)
I have a question regarding if it's possible to show images concerning their relative sizes.
I'm experimenting with the experimental branch.
![image](https://user-images.githubusercontent.com/26222919/72723531-34948980-3bc4-11ea-9ecf-c820a8d65216.png)
For example, the actual height of the above three original images is the same but, since get_atlas_data resizes every image with resize_to_height, they are all normalized to their max height or width.
I've tried testing with square_cells option with "true" but it's resulting weirdly with images patched on one another. It would be really helpful if you can give me some comments or ideas. 
Thank you in advance!!

**Comment by duhaime** [comment]
@bado-lee Thanks for this note! Yes, `square_cells` needs to be removed, as the client side code assumes each cell in the atlas images will have uniform height and variable width.

This is an interesting use case. I believe that the calls to `resize_to_height` in `get_atlas_data` should resize each of your words so that its height in the atlas is some fixed value (the default should be 32px). `resize_to_max` though, which controls the behavior for the level of detail mechanism, will resize the image so its largest dimension is 128px. 

That's all to say, I believe the trouble here comes from the level of detail mechanism. You could verify that by running `lod.state.run = false` in the console and then zooming in and panning around. Your images should remain constant height if I'm not mistaken.

The reason for this discrepancy is just that in the case of the level of detail mechanism, we create a 2048px canvas and then update little 128x128 cells within that canvas. (If you run `lod.state.run = true; document.body.appendChild(lod.tex.canvas)` in your browser's dev tools, then zoom around the plot a little, you'll see the level of detail canvas update realtime. We need to keep track of which level of detail canvas spots are open, so it seemed easiest to do this with uniform sized squares. One could hack the level of detail mechanism (`LOD`) to use constant height cells, but that would involve a lot of book-keeping and would be far less performant than the current approach (it will be hard to find an open spot of consecutive pixels into which to write a new texture).

Would you be able to say a little about what you're hoping to do? If you only want to render text, my hunch is that using a different approach may work out better. We built out a kind of [proof of concept for rendering text with WebGL](https://github.com/YaleDHLab/wordmap/stargazers). I'd be more inclined to hack that approach (which will involve far less texture data, and will therefore be able to render much more text).

In any event, once I know more about your goals and your data I'll be happy to try and recommend possibly fruitful paths...

**Comment by bado-lee** [comment]
Wow! Thanks for your detailed explanation.
I can grasp how it actually works.
Also, your link to "text with WebGL" is again, really fascinating!
However, my text images are not actually a text. 
They are cropped images from the document.
Actually, I think I can achieve what I want by simply padding the images to maintain relative sizes in advance of copying into the cells, with the max height or width to fit the cell.
Thank you so much!

**Comment by duhaime** [comment]
Good luck! I'd be curious to see how this turns out--keep me posted!
